package main;

import java.util.List;
import javax.swing.ImageIcon;

public class NationGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NationGUI.class.getName());
    
    private Nation myNation;

    /**
     * Creates new form NationGUI
     */
    public NationGUI() {
        initComponents();
        
        List<NationData> dataList = NationLoader.loadNations(".src/countrydata/nation.json");
        NationData nationData = dataList.get(0);
        myNation = new Nation(nationData);
        
        lbl_flag.setIcon(new ImageIcon(myNation.getFlag()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_countryinfo = new javax.swing.JPanel();
        lbl_flag = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_capital = new javax.swing.JLabel();
        pnl_currency = new javax.swing.JLabel();
        btn_events = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_nationoptions = new javax.swing.JButton();
        btn_settings = new javax.swing.JButton();
        pnl_countryoptions = new javax.swing.JPanel();
        btn_optionsreturn = new javax.swing.JButton();
        lbl_optionsname = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        lbl_optionscapital = new javax.swing.JLabel();
        fld_capital = new javax.swing.JTextField();
        lbl_optionscurrency = new javax.swing.JLabel();
        fld_currency = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnl_countryinfo.setPreferredSize(new java.awt.Dimension(970, 300));

        lbl_flag.setText("Flag");
        lbl_flag.setPreferredSize(new java.awt.Dimension(200, 120));

        lbl_name.setText("Name:");

        lbl_capital.setText("Capital:");

        pnl_currency.setText("Currency: ");

        btn_events.setText("Events");
        btn_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eventsActionPerformed(evt);
            }
        });

        btn_2.setText("jButton1");

        btn_3.setText("jButton3");

        btn_4.setText("jButton4");

        btn_nationoptions.setText("Nation Options");
        btn_nationoptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nationoptionsActionPerformed(evt);
            }
        });

        btn_settings.setText("Settings");

        javax.swing.GroupLayout pnl_countryinfoLayout = new javax.swing.GroupLayout(pnl_countryinfo);
        pnl_countryinfo.setLayout(pnl_countryinfoLayout);
        pnl_countryinfoLayout.setHorizontalGroup(
            pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_countryinfoLayout.createSequentialGroup()
                .addGroup(pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pnl_countryinfoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_events, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nationoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_countryinfoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_flag, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_capital)
                            .addComponent(pnl_currency)
                            .addComponent(lbl_name))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_countryinfoLayout.setVerticalGroup(
            pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_countryinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nationoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_events, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnl_countryinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_countryinfoLayout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_capital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_currency))
                    .addComponent(lbl_flag, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(615, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_countryinfo, "card2");

        btn_optionsreturn.setText("Return");
        btn_optionsreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_optionsreturnActionPerformed(evt);
            }
        });

        lbl_optionsname.setText("Country Name");

        lbl_optionscapital.setText("Capital City");

        lbl_optionscurrency.setText("Currency");

        jLabel1.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Options");

        javax.swing.GroupLayout pnl_countryoptionsLayout = new javax.swing.GroupLayout(pnl_countryoptions);
        pnl_countryoptions.setLayout(pnl_countryoptionsLayout);
        pnl_countryoptionsLayout.setHorizontalGroup(
            pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                        .addGroup(pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_optionscurrency)
                            .addComponent(lbl_optionscapital)
                            .addComponent(lbl_optionsname))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                        .addGroup(pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                                .addComponent(btn_optionsreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(667, 667, 667)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                                .addGroup(pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fld_currency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(fld_capital, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fld_name, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnl_countryoptionsLayout.setVerticalGroup(
            pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_countryoptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_countryoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_optionsreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_optionsname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_optionscapital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fld_capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_optionscurrency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(577, 577, 577))
        );

        getContentPane().add(pnl_countryoptions, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eventsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eventsActionPerformed

    private void btn_nationoptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nationoptionsActionPerformed
        pnl_countryinfo.setVisible(false);
        pnl_countryoptions.setVisible(true);
    }//GEN-LAST:event_btn_nationoptionsActionPerformed

    private void btn_optionsreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_optionsreturnActionPerformed
        pnl_countryoptions.setVisible(false);
        pnl_countryinfo.setVisible(true);
    }//GEN-LAST:event_btn_optionsreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NationGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_events;
    private javax.swing.JButton btn_nationoptions;
    private javax.swing.JButton btn_optionsreturn;
    private javax.swing.JButton btn_settings;
    private javax.swing.JTextField fld_capital;
    private javax.swing.JTextField fld_currency;
    private javax.swing.JTextField fld_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_capital;
    private javax.swing.JLabel lbl_flag;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_optionscapital;
    private javax.swing.JLabel lbl_optionscurrency;
    private javax.swing.JLabel lbl_optionsname;
    private javax.swing.JPanel pnl_countryinfo;
    private javax.swing.JPanel pnl_countryoptions;
    private javax.swing.JLabel pnl_currency;
    // End of variables declaration//GEN-END:variables
}
